services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # poll every 60 sec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: watchtower
  express-app:
    image: ichirojwang/express-app:latest
    ports:
      - 8080:8080